Feature: Check out screen
CraftAcademy/slow_food_sinatra_nov pull request #20
Opened 2016-12-01 12:13 UTC by Philippoes

[Waffle Story](https://waffle.io/CraftAcademy/slow_food_sinatra_nov/cards/583c26c58e5f040e0010a23c)

Description: This pull request will add implementation for the "Check out!" button which will take visitors to a checkout page where they can see the items + total amount.

What we have learned working on this feature: We have learned how to redirect a visitor to another site using a button.

2016-12-02 10:43 UTC, tochman commented
Please use the PR template for description.

2016-12-03 11:46 UTC, tochman requested changes
Good job but you need to address my comments before we can merge this.

2016-12-03 11:46 UTC, tochman commented on features/checkout_screen.feature
> +    And I should see a "Buy now!" button
Code indentation is different in the scenarios. Please normalize (compare the first scenario with the second)

2016-12-03 11:46 UTC, tochman commented on features/checkout_screen.feature
> +    And I should see "Total: $4.99"
What is the difference between `And I shold see a total amount of "4.99"` vs `And I should see "Total: $4.99"`?

2016-12-03 11:46 UTC, tochman commented on features/checkout_screen.feature
> +  Given that I don't see "added to basket"
Why is this relevant?

2016-12-03 11:46 UTC, tochman commented on features/checkout_screen.feature
> +    And I have a dish called "Salad" with price "4.99"
This step can be refactored into a table (Not a blocker though)

2016-12-03 11:46 UTC, tochman commented on features/see_dishes.feature
> +    Then I see "Checkout" button
`I see`seems weird as an assertion. Consider `I should see`

2016-12-03 11:46 UTC, tochman commented on features/step_definitions/add_dish_to_basket_steps.rb
>  When(/^I click "([^"]*)"$/) do |add_button|
Why do you name this variable to `add_button`?

2016-12-03 11:46 UTC, tochman commented on features/step_definitions/checkout_screen_test.rb
> +end
Code indentation

2016-12-03 11:46 UTC, tochman commented on lib/controller.rb
> +        @total = @total + order_item.dish.price
Imo, the `total` method should be added to the model and not be calculated in the controller. You should be able to access a method `@current_order.total`

2016-12-03 11:46 UTC, tochman commented on lib/views/checkout.erb
> +<p>Total: $<%="%.2f" % @total%></p>
The formatting of the order total should also be part of a model.

2016-12-03 11:50 UTC, Philippoes commented on features/checkout_screen.feature
> +    And I should see "Total: $4.99"
Right. This is a typo. We're gonna fix this. "Total: $4.99" is the total amount of all items in the basket.  The other one is simply the price of the item.

2016-12-03 14:30 UTC, Philippoes commented
Resolved all issues, please check it again.

2016-12-04 08:41 UTC, tochman commented on features/step_definitions/checkout_screen_test.rb
> +end
This looks weird to me. Why do you have an assertion in a "Given" step? How is this step definition used?

2016-12-04 08:42 UTC, tochman approved these changes

2016-12-04 08:51 UTC, rmzse commented on features/step_definitions/checkout_screen_test.rb
> +end
We want to remind the user to add stuff to basket before trying to check out by hitting the checkout button. For that special use case to happen we need the user to have an empty basket, so that this error msg reminding the user to add stuff to basket is shown. 

Is this "Given" different from other ones we have written before? If so, can you help us point out the difference?

2016-12-04 12:04 UTC, tochman commented on features/step_definitions/checkout_screen_test.rb
> +end
Give this post a read and consider what I say about "Given" steps. https://medium.com/craft-academy/whats-so-good-about-cucumber-904c34d29f7b#.symptawut

2016-12-04 13:55 UTC, tochman commented
The current state of this PR is good. I miss some `sad path` scenarios for checkout but they can be added as a separate chore. Good job delivering this and fixing the code after my comments.

2016-12-04 13:55 UTC, merged